# -*- coding: utf-8 -*-
"""real_or_not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M71LNDUUk8v5mwclmyGhho1_ew19OwKH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import nltk
nltk.download('all')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

df_train = pd.read_csv('/content/drive/My Drive/nlp-getting-started/train.csv')
df_test = pd.read_csv('/content/drive/My Drive/nlp-getting-started/test.csv')

df_train.tail(20)

df_test.head()

# df_train = df_train[['text','target']]

x = df_train['text']
y = df_train['target']
x_t = df_test['text']
x_train,x_test,y_train,y_test = train_test_split(x,y)

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.svm import  SVC
vect = TfidfVectorizer(min_df=5,ngram_range=(1,3)).fit(x_train)
x_train_vect = vect.transform(x_train)

clf = LogisticRegression().fit(x_train_vect,y_train)
# clf = MultinomialNB(alpha=0.1).fit(x_train_vect,y_train)
# clf = ExtraTreesClassifier().fit(x_train_vect,y_train)
# clf = SVC(C=1000).fit(x_train_vect,y_train)


print(clf.score(vect.transform(x_test),y_test))
# print(len(y_test))

y_t = clf.predict(vect.transform(x_t))

idx = df_test['id'].values
len(y_t)

data = {'id':idx , 'target':y_t}
ret = pd.DataFrame(data)

ret = ret.set_index('id')

ret.to_csv('submit.csv')

ret

clf.predict(vect.transform(['Breaking News, india attacks pakistan']))

a = np.max(df_test['text'])
len(a)

